---
- name: Create Docker + Compose files
  template:
    src: "{{ item.key }}"
    dest: "{{ item.value.dest }}"
    mode: "{{ item.value.mode }}"
  with_dict:
    local-core-dockerfile.j2:
      dest: docker/local-core/Dockerfile
      mode: "0644"
    local-core-compose.j2:
      dest: docker/local-core/docker-compose.yml
      mode: "0644"

- name: Fetch the latest Cardano binaries
  script: scripts/get_files.sh {{ files_path }}/bins/ {{ cardano_hydra_build }} {{ cardano_node_version }}
  register: result

- name: Fetch Script Output
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Fetch the latest Cardano configurations
  script: scripts/get_configs.sh {{ files_path }}/configs/
  register: result

- name: Fetch Script Output
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Copy templated files
  template:
    src: "{{ item.key }}"
    dest: "{{ item.value.dest }}"
    mode: "{{ item.value.mode }}"
  with_dict:
    scripts-common.inc.j2:
      dest: "docker/local-core/config/.common.inc"
      mode: "0400"
    setup-inputrc.j2:
      dest: "docker/local-core/etc/inputrc"
      mode: "0644"
    setup-bashrc.j2:
      dest: "docker/local-core/config/.bashrc"
      mode: "0644"

- name: Copying Cardano Binaries
  copy:
    src: "{{ files_path }}/{{ item }}"
    dest: "docker/local-core/bins/{{ item }}"
    mode: "0755"
  with_items:
    - cardano-node
    - cardano-cli

- name: Copying Default Config Files and Topology
  copy:
    src: "{{ files_path }}/configs/{{ item }}"
    dest: "docker/local-core/config/{{ item }}"
    mode: "0644"
  with_items:
    - mainnet-config.json
    - mainnet-byron-genesis.json
    - mainnet-shelley-genesis.json
    - mainnet-alonzo-genesis.json
    - mainnet-topology.json

- name: Copying External Scripts
  copy:
    src: "scripts/{{ item }}"
    dest: "docker/local-core/scripts/{{ item }}"
    mode: "0755"
  with_items:
    - 0x_genPledgeAccount.sh

- name: Docker Compose Build Local Core
  docker_compose:
    project_src: docker/local-core/
    project_name: local
    files:
      - "docker-compose.yml"
    build: yes
    state: present
  register: result

- name: Docker Compose Compile Result
  debug:
    msg: "Docker container successfully built: {{ result.services.core.local_core_1.image }}"
